---

- name: Create temporary build directory
  ansible.builtin.tempfile:
    state: directory
    prefix: gitlab-crts
  register: temp_path

- community.crypto.openssl_privatekey:
    path: "{{ temp_path.path }}/{{hostname}}-tls.pem"
    size: 2048

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ temp_path.path }}/{{hostname}}-csr.csr"
    privatekey_path: "{{ temp_path.path }}/{{hostname}}-tls.pem"
    common_name: "{{ hostname }}"
    organization_name: "{{ hostname }}"
    subject_alt_name: "DNS:{{ hostname}}"

- name: Generate certificate using csr and private key file
  community.crypto.x509_certificate:
    provider: selfsigned
    path: "{{ temp_path.path }}/{{hostname}}-crt.pem"
    privatekey_path: "{{ temp_path.path }}/{{hostname}}-tls.pem"
    csr_path: "{{ temp_path.path }}/{{hostname}}-csr.csr"
  register: certificates

- name: Fetch the private key and certificate for gitlab secret file
  set_fact:
    private_key: "{{ lookup('file', '{{ temp_path.path }}/{{hostname}}-tls.pem') | replace('\n', '') | replace('-----BEGIN RSA PRIVATE KEY-----', '') | replace('-----END RSA PRIVATE KEY-----','') }}"
    cert: "{{ lookup('file', '{{ temp_path.path }}/{{hostname}}-crt.pem') | replace('\n', '') | replace('-----BEGIN CERTIFICATE-----', '') | replace('-----END CERTIFICATE-----','') }}"

- kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
        kind: Secret
        metadata:
          name: gitlab-secret-tls
          namespace: hpeda
        type: kubernetes.io/tls
        data:
          tls.crt: "{{ cert }}"
          tls.key: "{{ private_key }}"
    validate:
      fail_on_error: yes