---

- block:
  - name: "Checking folders"
    stat:
      path: "{{item}}"
    register: folder_stats
    loop: "{{ gitlab_path }}"

  - name: "Creating multiple folders without disturbing previous permissions"
    file:
      path: "{{item.item}}"
      state: directory
      recurse: yes
    when: item.stat.exists == false
    loop: "{{ folder_stats.results }}"